import "~/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { Rubik } from "next/font/google";
import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "react-hot-toast";

const rubik = Rubik({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Interactive comments section",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/images/favicon-32x32.png" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" className="bg-Fm-Very-light-gray">
        <body className={`font-sans ${rubik.variable}`}>
          <Toaster position="bottom-center" />
          <TRPCReactProvider cookies={cookies().toString()}>
            {children}
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
